FROM alpine:3.24.2@sha256:3cf95fe0816180395592b8373f3ec60663f076127617bbacb4eacf9667afe2e9

# renovate: datasource=repology depName=alpine_3_24/yq-go versioning=loose
ARG YQ_VERSION=4.53.3-r1

RUN apk -U add --no-cache \
  yq-go="${YQ_VERSION}"

ENTRYPOINT [ "/usr/bin/yq" ]
