FROM alpine:3.24.2@sha256:31b6477333eb8257db9e5d7c3a7264fd0467928756f0bbcc27d35bea5d28cdbd

# renovate: datasource=repology depName=alpine_3_24/yq-go versioning=loose
ARG YQ_VERSION=4.53.3-r1

RUN apk -U add --no-cache \
  yq-go="${YQ_VERSION}"

ENTRYPOINT [ "/usr/bin/yq" ]
