FROM alpine:3.24.1@sha256:bec4ccd3817e7c824eb0388971a0b83fab111d586285511ba0266b77e8dc65a9

# renovate: datasource=repology depName=alpine_3_24/unbound versioning=loose
ARG UNBOUND_VERSION=1.25.1-r0

RUN apk -U add --no-cache \
  unbound="${UNBOUND_VERSION}"

ENTRYPOINT [ "/usr/sbin/unbound" ]
CMD [ "-d", "-c", "/etc/unbound/unbound.conf" ]
