FROM alpine:3.24.2@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6

# renovate: datasource=repology depName=alpine_3_24/unbound versioning=loose
ARG UNBOUND_VERSION=1.25.2-r1

RUN apk -U add --no-cache \
  unbound="${UNBOUND_VERSION}"

ENTRYPOINT [ "/usr/sbin/unbound" ]
CMD [ "-d", "-c", "/etc/unbound/unbound.conf" ]
